### ISSUE TITLE
RT Ticket #281: questions remarks regarding Debian package downloads

### ISSUE THREAD

**Issue by phinjensen** [interchange/devsite#1]
Created: Wed Jun 17 06:48:53 2009
Owner: Stefan Hornburg
Requestors: Gert van der Spoel

---

Also I have a few questions/remarks:
1) On http://www.icdevgroup.org/i/dev/download

"You can find the packages and apt-get setup instructions in a
separate directory" where directory is a link to a directory on the
server with some files.

Which is the file containing the apt-get setup instructions? 

2) The following text is in the README.debian
(http://ftp.icdevgroup.org/interchange/5.6/debian/README.debian)
# CVS

You can build Debian packages directly from CVS with the following commmand:

dpkg-buildpackage -rfakeroot -uc -us

Would this still work as we move to GIT?

**Comment by jonjensen** [comment]
This is no longer relevant because the download page has said for years that we no longer maintain the Debian and RPM packages.
