### ISSUE TITLE
Hall of Fame updates

### ISSUE THREAD

**Issue by klaatuic** [interchange/devsite#2]
Cranbourne is no longer IC based so should be deleted.

And filterific.com.au possibly worthy of moving up to "Noteworthy" as based on Strap and features improved AJAX search which not many sites do.

Filterific
By: <a href="https://www.computerjazz.net/">computerjazz.net</a><br />
MegaMenu managed by admin UI plus includes AJAX search developed by <a href="https://www.endpoint.com/">EndPoint</a>

**Comment by jonjensen** [comment]
Not sure how this was missed before. Now it's done.

**Comment by klaatuic** [comment]
FYI filterific.com.au no longer IC based as of past month so can be removed.

**Comment by jonjensen** [comment]
Heh. Funny timing on that move away!

Ok, it's removed now.
